### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by liming** [liming/hellosleep-site#1]
睡吧网站刚刚起步，还需要大量的修改和功能增加才能达到好用的程度。下面是需要做的任务列表：
- [x] 增加 [有用] 按钮，用来获得用户对一篇文章的反馈。
- [ ] 根据上下文和分类增加一篇文章的链接。比如"感兴趣"的文章和"上一篇"，"下一篇"等等。
- [x] 评论系统。允许不登录评论。
- [ ] 添加node mailer可以实现邮件功能。
- [ ] 增加分享按钮，允许用户分享到微信或者微博。
- [ ] 增加睡眠评估，允许用户在网站上进行评估，并发布到网站，当评估被回复之后可以收到评估的回复。

**Comment by liming** [comment]
豆瓣小组暂时没有api来发布。
https://gist.github.com/iamsk/1bc0760dfeeeb950f18e

那么评估的流程可能需要做到内部。
